name: Truffle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm packages
        run: npm install
      - name: Migrate Contracts
        run: ./node_modules/truffle/build/cli.bundled.js migrate --network quickstartWallet
      - name: Test Contracts
        run: ./node_modules/truffle/build/cli.bundled.js test --network quickstartWallet

