truffle:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: ./contracts

  steps:
    - uses: actions/checkout@v2
    - name: Set up NodeJS 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Cache npm packages
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install npm packages
      run: npm install
    - name: Migrate Contracts
      run: ./node_modules/truffle/build/cli.bundled.js migrate --network quickstartWallet
    - name: Test Contracts
      run: ./node_modules/truffle/build/cli.bundled.js test --network quickstartWallet
    - name: Stop ganache
      run: kill $(lsof -t -i:8545)